### PR TITLE
bump geth to prepare for the merge

### PR DESCRIPTION
**Pull request by q9f**
is there anything else required? does it need a beacon client?

also @eduadiez could you create a release from the dappnode organization now?

### CODE REVIEW

**Comment by tropicar** [comment]
For the merge as far as I know, we would require:
- Create a package of the consensus layer(prysm for example or another one). I think is not required to use  web3signer because sepolia is not for testing validating according to the ethereum foundation announcement.
- For the merge are required more configurations, here and in the eth2. client: JWT token in both packages, some authentication flags relative to the new endpoint which will be used, and engine api enable (this configuration is specific of any client, I mean, every client uses different flags) That would be all I think.

**Comment by eduadiez** [comment]
My bad, thanks for the ping. We're reviewing it now, and it'll be publish today. Thank you!!

**Comment by tropicar** [comment]
I think that would be all the required changes, I have added:
- JWT token file with a hardcoded value(it just be the same file in the beacon node)
- Enable the engine API 
- Add the authrpc flags: addr, port, vhosts and jwtsecret

**Comment by q9f** [comment]
LGTM! Thank you!

**Comment by tropicar** [comment]
I have created the beacon-chain package https://github.com/dappnode/DAppNodePackage-prysm-sepolia/pull/2 but it gives me an error. 
With all these changes, I can sync the sepolia geth node. But I am having a problem running the prysm with sepolia.

**Pull request merged**
